version: "3"

services:
    yarn:
        image: node:15.4.0
        user: node
        working_dir: /home/node
        entrypoint: yarn
        command: --help
        tty: true
        stdin_open: true
        volumes:
            - .:/home/node

    bash:
        image: node:15.4.0
        user: node
        working_dir: /home/node
        entrypoint: bash
        env_file: .env
        volumes:
            - .:/home/node

