name: Package

on:
    push:
        branches:
            - next

jobs:
    package:
        name: Build the package and publish a new version if needed
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the project
              uses: actions/checkout@v2

            - name: Setup the environment
              run: cp .env.example .env

            - name: Cleanup project
              run: make clean

            - name: Setup the NPM authentication token
              run: sed -i "s/NPM_AUTH_TOKEN=.*/NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN }}/g" .env

            - name: Register the current Git user name
              run: git config user.name ${{ secrets.WORKFLOW_GITHUB_USERNAME }}

            - name: Register the current Git user email
              run: git config user.email ${{ secrets.WORKFLOW_GITHUB_EMAIL }}

            - name: Setup the NPM running configuration for using the authentication token
              run: make token

            - name: Install the Node.js dependencies
              run: make install

            - name: Build project
              run: make build

            - name: Creating tag
              run: git tag -a $(cat package.json | grep -i version | sed -e "s/ //g" | cut -c 12- | sed -e "s/\",//g") -m "$(cat package.json | grep -i version | sed -e "s/ //g" | cut -c 12- | sed -e "s/\",//g")"

            - name: Publish tag
              run: 'git push origin $(cat package.json | grep -i version | sed -e "s/ //g" | cut -c 12- | sed -e "s/\",//g") || true'

            - name: Publish a new version of the package if needed
              run: 'make publish || true'
